/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHAT_H_RPCGEN
#define _CHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Message {
	char message[100];
};
typedef struct Message Message;

#define CHAT_PROG 0x1231231
#define CHAT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define chat 1
extern  Message * chat_1(Message *, CLIENT *);
extern  Message * chat_1_svc(Message *, struct svc_req *);
extern int chat_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define chat 1
extern  Message * chat_1();
extern  Message * chat_1_svc();
extern int chat_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Message (XDR *, Message*);

#else /* K&R C */
extern bool_t xdr_Message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHAT_H_RPCGEN */
